"""ARRAYS

Revision ID: f73f4ea0b7fb
Revises: 0f2c90d5714d
Create Date: 2025-07-20 14:32:56.936717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73f4ea0b7fb'
down_revision: Union[str, Sequence[str], None] = '0f2c90d5714d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_activity')
    op.drop_table('role_activity')
    op.add_column('employees', sa.Column(
        'activity_ids',
        sa.ARRAY(sa.Integer()),
        nullable=False,
        server_default='{}'
    ))
    op.add_column('roles', sa.Column('activity_ids', sa.ARRAY(sa.Integer()), nullable=False, server_default='{}'))
    op.add_column('servers', sa.Column('employee_ids', sa.ARRAY(sa.Integer()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'employee_ids')
    op.drop_column('roles', 'activity_ids')
    op.drop_column('employees', 'activity_ids')
    op.create_table('role_activity',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activitys.id'], name=op.f('role_activity_activity_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_activity_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'activity_id', name=op.f('role_activity_pkey'))
    )
    op.create_table('employee_activity',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activitys.id'], name=op.f('employee_activity_activity_id_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('employee_activity_employee_id_fkey')),
    sa.PrimaryKeyConstraint('employee_id', 'activity_id', name=op.f('employee_activity_pkey'))
    )
    # ### end Alembic commands ###
